import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PLAYER_NAME_FORMATS, formatFieldValue } from '../js/formatter.js';
import { DESIGNER_SAMPLE_MODEL } from '../js/sample-data.js';
import { getFieldDefinition, resolveField } from '../js/field-registry.js';
import { formattingGroupForFieldId, formattingGroupForContext } from '../js/formatting.js';

const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
assert.match(html, /id="layout-settings-name"/);
assert.match(html, /id="layout-settings-pdf-input"/);
assert.match(html, /id="layout-custom-fields-open"/);
assert.match(html, /id="layout-custom-fields-save"/);
assert.match(html, /id="layout-formatting-toggle"/);
assert.match(html, /id="designer-collapse-all-top"/);
assert.match(html, /id="designer-collapse-all-bottom"/);
assert.doesNotMatch(html, /Browse what is available\. A field is only considered used/);
assert.match(app, /elements\.designerPlaceRowsButton\.hidden = !block\?\.geometry/);
assert.doesNotMatch(app, /id\.startsWith\("away\.manager"\).*away-players/);
assert.equal(formattingGroupForFieldId('away.manager.name'), 'away-team');
assert.equal(formattingGroupForFieldId('home.manager.name'), 'home-team');
assert.equal(formattingGroupForContext('away.manager'), 'away-team');
assert.deepEqual(PLAYER_NAME_FORMATS.map(x => x.label), ['Full Name','First Initial + Last Name','Last Name','First Name','Use Name','Boxscore Name']);
const def = getFieldDefinition('away.lineup[].player.name');
const player = DESIGNER_SAMPLE_MODEL.away.lineup[0].player;
const res = { state: 'available', value: player.name, formatSource: player };
assert.equal(formatFieldValue(def,res,DESIGNER_SAMPLE_MODEL,{nameFormat:'first-initial-last'}), 'R Yu');
assert.equal(formatFieldValue(def,res,DESIGNER_SAMPLE_MODEL,{nameFormat:'use'}), 'Bo');
assert.notEqual(player.firstName, player.useName);
console.log('Build 026.1 acceptance contract passed.');
