import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('../', import.meta.url);
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8');
const html = read('index.html');
const app = read('js/app.js');
const css = read('css/styles.css');
const sample = read('js/sample-data.js');
const meta = JSON.parse(read('app-meta.json'));
assert.ok(['024.1','024.2'].includes(meta.build));
assert.match(html, /id="designer-zoom-menu"/);
assert.match(html, /id="designer-zoom-in-btn"/);
assert.match(html, /id="designer-zoom-out-btn"/);
assert.match(app, /handleDesignerPasteToolbarClick/);
assert.match(css, /designer-paste-options button\[hidden\]/);
assert.match(app, /Choose text field to insert/);
assert.match(app, /preserveParentContext: true/);
assert.match(app, /mapping\.collection === collection/);
assert.match(sample, /Christopher Van Buren/);
assert.match(sample, /lastName: "Van Buren"/);
assert.match(sample, /lastName: "St\. James"/);
assert.match(sample, /lastName: "De la Cruz"/);
assert.match(sample, /nameSuffix: "III"/);
console.log('Build 024.1 checks passed.');
