import fs from 'node:fs';
import assert from 'node:assert/strict';
const app = fs.readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../css/styles.css', import.meta.url), 'utf8');
const meta = JSON.parse(fs.readFileSync(new URL('../app-meta.json', import.meta.url), 'utf8'));

assert.equal(meta.version, '0.2.0-dev');
assert.match(meta.build, /^02[3-9](?:\.|$)/);
assert.match(html, /data-app-version-label/);
assert.match(html, /data-app-build-label/);
assert.match(html, /data-app-build-prefix="Live Coverage"/);
assert.match(html, /data-app-build-upper-prefix="Designer Workspace"/);
assert.match(app, /async function loadAppMetadata/);
assert.match(app, /function copyDesignerSelection/);
assert.match(app, /function beginDesignerClipboardPlacement/);
assert.match(app, /async function commitDesignerClipboardPlacement/);
assert.match(app, /function clipboardTranslationEligibility/);
assert.match(app, /function translateDesignerTemplate/);
assert.match(app, /mode === "awayToHome"/);
assert.match(app, /mode === "homeToAway"/);
assert.match(app, /String\(event\.key\)\.toLowerCase\(\) === "c"/);
assert.match(app, /String\(event\.key\)\.toLowerCase\(\) === "v"/);
assert.match(html, /id="designer-copy-btn"/);
assert.match(html, /id="designer-paste-btn"/);
assert.match(html, /id="designer-paste-away-home-btn"/);
assert.match(html, /id="designer-paste-home-away-btn"/);
assert.match(css, /\.designer-paste-ghost/);
console.log('Build 022 copy, paste, team translation, ghost placement, and app metadata checks passed.');
