import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('../', import.meta.url);
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8');
const html = read('index.html');
const app = read('js/app.js');
const slot = read('js/slot-content.js');
const meta = JSON.parse(read('app-meta.json'));
assert.ok(['024','024.1','024.2'].includes(meta.build));
assert.match(html, /id="designer-copy-btn"/);
assert.match(html, /id="designer-paste-menu"/);
assert.doesNotMatch(html, /id="designer-individual-strategy"/);
assert.doesNotMatch(html, /id="designer-individual-slot"/);
assert.doesNotMatch(html, /class="designer-status-row"/);
assert.match(app, /const strategy = "role"/);
assert.match(app, /deleteDesignerBlockColumn\(selection\.blockId, selection\.columnId(?:, \{ preserveParentContext: true \})?\)/);
assert.match(slot, /tokenValues\.every/);
assert.match(app, /templateTokenWithNameFormat/);
console.log('Build 024 checks passed.');
